# Generated by Django 3.0.2 on 2020-01-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20200116_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('NB', 'Não-binário'), ('O', 'Outros')], max_length=255, verbose_name='Gênero'),
        ),
    ]
